import type { OlySet } from "./types";

const ORDER = { sym: "( ) and [ ]", meaning: "work out what is inside first; [ ] is just a bigger bracket around ( )" };
const SO = { sym: "⇒", meaning: "so, which gives" };

/** The Maths Olympiad sets, for Classes 7 to 10 (IOQM and NMTC junior style). */
export const MATHS_OLY_SETS: OlySet[] = [
  {
    id: "number-sense",
    subject: "maths",
    title: "Number sense and divisibility",
    emoji: "🔢",
    blurb: "Laddoos in boxes, a PT drill in neat rectangles and diyas that never come out even.",
    colour: "#67e8f9",
    sim: "Packing sim",
    symbols: [
      { sym: "N", meaning: "the number we are looking for" },
      { sym: "÷", meaning: "divide" },
      { sym: "remainder", meaning: "what is left over after making as many full groups as possible" },
      { sym: "LCM", meaning: "lowest common multiple: the smallest number every size divides into exactly" },
      { sym: "a × b", meaning: "a times b; for a rectangle, a rows of b" },
      { sym: "k", meaning: "a whole number 0, 1, 2, 3, ..." },
      SO,
      ORDER,
    ],
  },
  {
    id: "angles-polygons",
    subject: "maths",
    title: "Angles and polygons",
    emoji: "🔷",
    blurb: "A stone jali window, floor tiles that must close up around a point and a pair of rangoli frames.",
    colour: "#a78bfa",
    sim: "Polygon sim",
    symbols: [
      { sym: "n", meaning: "number of sides of a regular polygon" },
      { sym: "°", meaning: "degrees" },
      { sym: "180° − (360° ÷ n)", meaning: "each inside angle of a regular polygon with n sides" },
      { sym: "360° ÷ n", meaning: "each outside (exterior) angle: they always add up to 360°" },
      { sym: "n-gon", meaning: "a polygon with n sides, like a 12-gon" },
      SO,
      ORDER,
    ],
  },
  {
    id: "triangles",
    subject: "maths",
    title: "Triangles and Pythagoras",
    emoji: "📐",
    blurb: "A ladder to a temple window, a bamboo snapped by the monsoon wind and a prop under two mela wires.",
    colour: "#f472b6",
    sim: "Right-triangle sim",
    symbols: [
      { sym: "a² + b² = c²", meaning: "Pythagoras: in a right triangle, the two shorter sides squared add up to the longest side squared" },
      { sym: "x²", meaning: "x squared, x × x" },
      { sym: "√", meaning: "square root: the number that, squared, gives what is under the sign" },
      { sym: "L, x, h", meaning: "the lengths we are looking for, in m: a ladder, a break height, a pole" },
      { sym: "p, q", meaning: "the two parts of the gap between the poles, in m" },
      { sym: "similar triangles", meaning: "same shape, different size: their sides are in the same ratio" },
      SO,
      ORDER,
    ],
  },
  {
    id: "areas-circles",
    subject: "maths",
    title: "Areas and circles",
    emoji: "⭕",
    blurb: "A ring of rangoli colour, a lawn round a temple tank and a leaf hidden in a square tile.",
    colour: "#fb923c",
    sim: "Fill sim",
    symbols: [
      { sym: "π", meaning: "pi, the ratio of a circle's distance round to its width; take 22/7" },
      { sym: "r, R", meaning: "radius: centre to edge, in cm or m" },
      { sym: "π r²", meaning: "area of a circle" },
      { sym: "s", meaning: "side of a square" },
      { sym: "cm², m²", meaning: "square centimetres, square metres: units of area" },
      SO,
      ORDER,
    ],
  },
  {
    id: "counting",
    subject: "maths",
    title: "Counting",
    emoji: "🏏",
    blurb: "Opening pairs, a school cricket league and routes to the temple round a flooded crossing.",
    colour: "#a3e635",
    sim: "Listing sim",
    symbols: [
      { sym: "×", meaning: "times: for 'this and then that' choices, multiply" },
      { sym: "n", meaning: "number of teams or players" },
      { sym: "C(n, k)", meaning: "n choose k: ways to pick k things from n when order does not matter" },
      { sym: "E, N", meaning: "one block east, one block north" },
      { sym: "EENNE...", meaning: "a route written step by step: E for a block east, N for a block north" },
      SO,
      ORDER,
    ],
  },
  {
    id: "probability",
    subject: "maths",
    title: "Probability",
    emoji: "🎲",
    blurb: "A dice game on a rainy day, toffees from Nani's jar and a captain's run of tosses across a series.",
    colour: "#facc15",
    sim: "Outcome grid sim",
    symbols: [
      { sym: "p", meaning: "probability: a number from 0 (never) to 1 (always)" },
      { sym: "p = favourable ÷ total", meaning: "when all outcomes are equally likely" },
      { sym: "1 − p", meaning: "the chance that it does not happen" },
      { sym: "W, L", meaning: "a toss won, a toss lost" },
      { sym: "M1, I2, ...", meaning: "names for each toffee (mango, imli), so that every pick is equally likely" },
      { sym: "2⁵", meaning: "2 × 2 × 2 × 2 × 2 = 32, the number of ways five tosses can go" },
      SO,
      ORDER,
    ],
  },
  {
    id: "equations",
    subject: "maths",
    title: "Equations and word problems",
    emoji: "⚖️",
    blurb: "A sabzi mandi balance, two trains on one line and a train that passes a cyclist and a walker.",
    colour: "#38bdf8",
    sim: "Balance and train sim",
    symbols: [
      { sym: "w, x, L", meaning: "the unknowns: a weight in kg, a distance in km, a length in m" },
      { sym: "v", meaning: "speed, in km/h or m/s" },
      { sym: "distance = speed × time", meaning: "for anything moving at a steady speed" },
      { sym: "relative speed", meaning: "how fast two movers close in on each other: add the speeds when they move towards each other, subtract when one chases the other" },
      { sym: "× 5/18", meaning: "turns km/h into m/s; 18 km/h = 5 m/s" },
      SO,
      ORDER,
    ],
  },
  {
    id: "sequences",
    subject: "maths",
    title: "Sequences and patterns",
    emoji: "🌀",
    blurb: "A row of matchstick squares, a stand of chairs for a kabaddi final and a hexagon of diyas that grows ring by ring.",
    colour: "#2dd4bf",
    sim: "Pattern builder sim",
    symbols: [
      { sym: "n", meaning: "the stage, row or ring number" },
      { sym: "a", meaning: "the first term" },
      { sym: "d", meaning: "common difference: how much each term adds" },
      { sym: "Sₙ", meaning: "the total of the first n terms" },
      { sym: "Sₙ = n × [2a + ((n − 1) × d)] ÷ 2", meaning: "sum of an arithmetic sequence" },
      SO,
      ORDER,
    ],
  },
  {
    id: "coordinates-heights",
    subject: "maths",
    title: "Coordinates and heights",
    emoji: "🗼",
    blurb: "Distances on a town map, a gopuram measured from the ground and a lighthouse seen from a boat.",
    colour: "#c084fc",
    sim: "Map and sight-line sim",
    symbols: [
      { sym: "(x, y)", meaning: "a point: x across, y up" },
      { sym: "d = √[(x₂ − x₁)² + (y₂ − y₁)²]", meaning: "distance between two points" },
      { sym: "θ", meaning: "theta, an angle of elevation: how far you look up from level" },
      { sym: "tan θ", meaning: "opposite side ÷ adjacent side, a calculator button" },
      { sym: "sin θ", meaning: "opposite side ÷ longest side (hypotenuse); sin 60° = √3 ÷ 2" },
      { sym: "√3", meaning: "about 1.732; tan 60° = √3 and tan 30° = 1 ÷ √3" },
      { sym: "h", meaning: "height, in m" },
      SO,
      ORDER,
    ],
  },
];
